import type { APIRoute } from "astro";

export const GET: APIRoute = async ({ request }) => {
  const base = import.meta.env.SITE ? new URL(import.meta.env.SITE).origin : new URL(request.url).origin;
  // Two complementary sitemaps: sitemap-index.xml (auto-generated by @astrojs/sitemap,
  // covers all prerendered static routes) and sitemap.xml (our hand-rolled route, covers
  // dynamic report pages + the pSEO content collection). List both for full coverage.
  const body = `User-agent: *\nDisallow: /r/\nDisallow: /api/\nAllow: /\nSitemap: ${base}/sitemap-index.xml\nSitemap: ${base}/sitemap.xml\n`;
  return new Response(body, {
    headers: {
      "Content-Type": "text/plain",
    },
  });
};
